### PR TITLE
Optional protected call for callFunction & fixing iterate over table

### PR DESCRIPTION
**Pull request by rilpires**
- This PR solves a problem with `Lua::getVariant(int index)`. When passing a relative index (index<0), the proper way to iterate with `lua_next()` is indeed using `index-1`, but when index>0, this should remain only `index`. This was crashing my project.

- Also, it gives a proper way to call lua functions from GDScript. Now we could check beforehand if the function actually exists, and we can optionally set it as a protected call. The arguments order were moved. Before, the first parameter `Object*` doesn't had any utility. I propose to use this same pattern of the same last 3 optional parameters ( bool protected_call , Object* callback_caller , String callback ) in doFile and doString as well, what do you think? To call functions outside protected mode could maybe be more performant, useful when targeting release.

### CODE REVIEW

**Comment by Trey2k** [comment]
This looks good, may want to add some documentation regarding the default values of callFunction and their use though

**Comment by Trey2k** [comment]
And I agree with using the same pattern for optional calls with doFIle and doString.

**Comment by rilpires** [comment]
I've added proper documentation and made both the `doString` and `doFile` functions to accept `bool protected_call , Object* callback_caller , String callback` as last optional parameters

**Comment by Trey2k** [comment]
To be honest I forgot docs could be built into the modules haha. Good work!

**Pull request merged**
